name: PR CI
run-name: "CI pipeline for PR - (#${{ github.event.number }}) ${{ github.event.pull_request.title }}"

permissions:
  contents: read
  actions: read
  id-token: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches: ["main", "master"]

jobs:
  pr_ci_wrkflw:
    name: Run CI
    uses: zscaler/terraform-modules-zscaler-ci-workflows/.github/workflows/pr_ci.yml@v0.1
    if: github.actor != 'dependabot[bot]'
    secrets: inherit
    with:
      cloud: aws
      tf_version: 1.13.0
      validate_max_parallel: 20
      test_max_parallel: 10
      fail_fast: false
      terratest_action: Plan # keep in mind that this has to start with capital letter
